// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using betrayal_hill.Data;

#nullable disable

namespace betrayal_hill.Migrations
{
    [DbContext(typeof(BetrayalContext))]
    partial class BetrayalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("betrayal_hill.Models.Dynamic.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HauntTriggered")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OmenCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("betrayal_hill.Models.Dynamic.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlacedRoomId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("PlacedRoomId");

                    b.HasIndex("PlayerId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("betrayal_hill.Models.Dynamic.PlacedRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Floor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Orientation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("RoomId");

                    b.ToTable("PlacedRooms");
                });

            modelBuilder.Entity("betrayal_hill.Models.Dynamic.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExplorerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Knowledge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Might")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sanity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExplorerId");

                    b.HasIndex("GameId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("betrayal_hill.Models.Static.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A growl, the scent of death. Pain. Darkness. Gone.",
                            Instruction = "When you draw this card, something bites you. The player on your right rolls a Might 4 attack against you for the mysterious something\r\n                                    (before it runs away into the darkness). You defend against this attack as normal, by rolling dice equal to your Might.\r\n                                    This omen can't be dropped, traded, or stolen. Make a haunt roll now.",
                            Name = "Bite",
                            Type = 2
                        },
                        new
                        {
                            Id = 2,
                            Description = "A diary or lab notes? Ancient script or modern ravings?",
                            Instruction = "Gain 2 Knowledge now. Lose 2 Knowledge if you lose the Book. Make a haunt roll now.",
                            Name = "Book",
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Hazy images appear in the glass.",
                            Instruction = "Once during your turn after the haunt is revealed, you can attempt a Knowledge roll to peer into the Crystal Ball:\r\n                                    4+ You see the truth. Search the item or event stack for a card of your choice. Shuffle that stack then place that card on top.\r\n                                    1–3 You avert your eyes. Lose 1 Sanity.\r\n                                    0 You stare into Hell. Lose 2 Sanity.\r\n                                    Make a haunt roll now.",
                            Name = "Crystal Ball",
                            Type = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "COMPANION This mangy dog seems friendly. At least you hope it is.",
                            Instruction = "Gain 1 Might and 1 Sanity now. Lose 1 Might and 1 Sanity if you lose custody of the Dog.\r\n                                    Take a small monster token to represent the Dog. Put it in your room. (Use a token of a different color from other monsters, if any.)\r\n                                    Once during your turn, the Dog can move to any explored room up to 6 spaces away, using doors and stairs, and then return.\r\n                                    It can pick up, carry and/or drop 1 item before it returns.\r\n                                    The Dog isn't slowed by opponents. It can't use one-way passages or rooms that require a roll. It can't carry items that slow movement.\r\n                                    This omen can't be dropped, traded, or stolen. Make a haunt roll now. ",
                            Name = "Dog",
                            Type = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "COMPANION A girl. Trapped. Alone. You free her!",
                            Instruction = "Gain 1 Sanity and 1 Knowledge now. Lose 1 Sanity and 1 Knowledge if you lose custody of the Girl.\r\n                                    This omen can't be dropped, traded, or stolen. Make a haunt roll now.",
                            Name = "Girl",
                            Type = 2
                        },
                        new
                        {
                            Id = 6,
                            Description = "A symbol of calm in an unsettling world.",
                            Instruction = "Gain 2 Sanity now. Lose 2 Sanity if you lose the Holy Symbol. Make a haunt roll now.",
                            Name = "Holy Symbol",
                            Type = 2
                        },
                        new
                        {
                            Id = 7,
                            Description = "COMPANION A raving, frothing, madman.",
                            Instruction = "Gain 2 Might and lose 1 Sanity now. Lose 2 Might and gain 1 Sanity if you lose custody of the Madman.\r\n                                    This omen can't be dropped, traded, or stolen. Make a haunt roll now.",
                            Name = "Madman",
                            Type = 2
                        },
                        new
                        {
                            Id = 8,
                            Description = "A somber mask to hide your intentions.",
                            Instruction = "Once during your turn, you can attempt a Sanity roll to use the Mask:\r\n                                    4+ You can put on or take off the Mask. If you put on the Mask, gain 2 Knowledge and lose 2 Sanity.\r\n                                    If you take off the Mask, gain 2 Sanity and lose 2 Knowledge.\r\n                                    0–3 You can't use the Mask this turn.\r\n                                    Make a haunt roll now.",
                            Name = "Mask",
                            Type = 2
                        },
                        new
                        {
                            Id = 9,
                            Description = "A medallion inscribed with a pentagram.",
                            Instruction = "You are immune to the effects of the Pentagram Chamber, Crypt, and Graveyard. Make a haunt roll now.",
                            Name = "Medallion",
                            Type = 2
                        },
                        new
                        {
                            Id = 10,
                            Description = "A battered ring with an incomprehensible inscription.",
                            Instruction = "If you attack an opponent that has a Sanity trait, you can attack with Sanity instead of Might.\r\n                                    (Your opponent then defends with Sanity, and damage is mental instead of physical.) Make a haunt roll now.",
                            Name = "Ring",
                            Type = 2
                        },
                        new
                        {
                            Id = 11,
                            Description = "A skull, cracked and missing teeth.",
                            Instruction = "If you take mental damage, you can take all of it as physical damage instead. Make a haunt roll now.",
                            Name = "Skull",
                            Type = 2
                        },
                        new
                        {
                            Id = 12,
                            Description = "WEAPON A weapon pulsing with power.",
                            Instruction = "You roll 2 additional dice (maximum of 8 dice) when making a Might attack with this weapon.\r\n                                    You can't use another weapon while you're using this one. Make a haunt roll now.",
                            Name = "Spear",
                            Type = 2
                        },
                        new
                        {
                            Id = 13,
                            Description = "A board with letters and numbers to call the dead.",
                            Instruction = "Before you move during your turn, you can look at the top tile of the room stack.\r\n                                    If you use the Spirit Board after the haunt has been revealed, the traitor can move any number of monsters 1 space closer to you.\r\n                                    (If you are the traitor, you don't have to move those monsters.) If there is no traitor, all monsters move 1 space closer to you.\r\n                                    Make a haunt roll now.",
                            Name = "Spirit Board",
                            Type = 2
                        },
                        new
                        {
                            Id = 14,
                            Description = "It's just prop armor from a Renaissance fair, bit it's still metal.",
                            Instruction = "Any time (not just once per turn) you take physical damage, take 1 less point of damage. This item can't be stolen.",
                            Name = "Armor",
                            Type = 1
                        },
                        new
                        {
                            Id = 15,
                            Description = "Smoke billows around you. You cough, wiping way tears.",
                            Instruction = "Put the Smoke token in this room. The Smoke blocks line of sight from adjacent rooms.\r\n                                    An explorer rolls 2 fewer dice (minimum of 1 die) on all trait rolls while in this room.",
                            Name = "Smoke",
                            Type = 0
                        });
                });

            modelBuilder.Entity("betrayal_hill.Models.Static.Explorer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Birthday")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Height")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hobbies")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Knowledge")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Might")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Sanity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Speed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StartingKnowledge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartingMight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartingSanity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartingSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Explorers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 23,
                            Birthday = "October 18th",
                            Height = "6'4\"",
                            Hobbies = "Football, Shiny Objects",
                            Knowledge = "[0,2,2,3,3,5,5,6,6]",
                            Might = "[0,4,5,5,6,6,7,8,8]",
                            Name = "Ox Bellows",
                            Sanity = "[0,2,2,3,4,5,5,6,7]",
                            Speed = "[0,2,2,2,3,4,5,5,6]",
                            StartingKnowledge = 3,
                            StartingMight = 3,
                            StartingSanity = 3,
                            StartingSpeed = 5,
                            Weight = 288
                        },
                        new
                        {
                            Id = 2,
                            Age = 20,
                            Birthday = "June 6th",
                            Height = "5'11\"",
                            Hobbies = "Track, Music, Shakespearean Literature",
                            Knowledge = "[0,2,3,3,4,5,5,5,7]",
                            Might = "[0,2,3,3,4,5,6,6,7]",
                            Name = "Darrin \"Flash\" Williams",
                            Sanity = "[0,1,2,3,4,5,5,5,7]",
                            Speed = "[0,4,4,4,5,6,7,7,8]",
                            StartingKnowledge = 3,
                            StartingMight = 3,
                            StartingSanity = 3,
                            StartingSpeed = 5,
                            Weight = 188
                        },
                        new
                        {
                            Id = 3,
                            Age = 13,
                            Birthday = "September 3rd",
                            Height = "4'11\"",
                            Hobbies = "Bugs, Basketball",
                            Knowledge = "[0,3,4,4,5,6,7,7,8]",
                            Might = "[0,2,3,3,4,5,5,6,8]",
                            Name = "Peter Akimoto",
                            Sanity = "[0,3,4,4,4,5,6,6,7]",
                            Speed = "[0,3,3,3,4,6,6,7,7]",
                            StartingKnowledge = 3,
                            StartingMight = 3,
                            StartingSanity = 4,
                            StartingSpeed = 4,
                            Weight = 98
                        },
                        new
                        {
                            Id = 4,
                            Age = 12,
                            Birthday = "May 21st",
                            Height = "5'1\"",
                            Hobbies = "Computers, Camping, Hockey",
                            Knowledge = "[0,1,3,3,5,5,6,6,7]",
                            Might = "[0,2,3,3,4,5,6,6,7]",
                            Name = "Brandon Jaspers",
                            Sanity = "[0,3,3,3,4,5,6,7,8]",
                            Speed = "[0,3,4,4,4,5,6,7,8]",
                            StartingKnowledge = 3,
                            StartingMight = 4,
                            StartingSanity = 4,
                            StartingSpeed = 3,
                            Weight = 109
                        },
                        new
                        {
                            Id = 5,
                            Age = 62,
                            Birthday = "April 29th",
                            Height = "5'9\"",
                            Hobbies = "Fencing, Gardening",
                            Knowledge = "[0,1,3,3,4,5,6,6,8]",
                            Might = "[0,1,2,2,4,4,5,5,7]",
                            Name = "Father Rhinehardt",
                            Sanity = "[0,3,4,5,5,6,7,7,8]",
                            Speed = "[0,2,3,3,4,5,6,7,7]",
                            StartingKnowledge = 4,
                            StartingMight = 3,
                            StartingSanity = 5,
                            StartingSpeed = 3,
                            Weight = 185
                        },
                        new
                        {
                            Id = 6,
                            Age = 57,
                            Birthday = "July 27th",
                            Height = "5'11\"",
                            Hobbies = "Gaelic Music, Drama, Fine Wines",
                            Knowledge = "[0,4,5,5,5,5,6,7,8]",
                            Might = "[0,1,2,3,4,5,5,6,6]",
                            Name = "Professor Longfellow",
                            Sanity = "[0,1,3,3,4,5,5,6,7]",
                            Speed = "[0,2,2,4,4,5,5,6,6]",
                            StartingKnowledge = 5,
                            StartingMight = 3,
                            StartingSanity = 3,
                            StartingSpeed = 4,
                            Weight = 153
                        },
                        new
                        {
                            Id = 7,
                            Age = 9,
                            Birthday = "February 14th",
                            Height = "4'2\"",
                            Hobbies = "Swimming, Medicine",
                            Knowledge = "[0,2,3,4,4,5,6,6,8]",
                            Might = "[0,2,3,3,3,4,5,6,7]",
                            Name = "Missy Dubourde",
                            Sanity = "[0,1,2,3,4,5,5,6,7]",
                            Speed = "[0,3,4,5,6,6,6,7,7]",
                            StartingKnowledge = 4,
                            StartingMight = 4,
                            StartingSanity = 3,
                            StartingSpeed = 3,
                            Weight = 62
                        },
                        new
                        {
                            Id = 8,
                            Age = 8,
                            Birthday = "November 5th",
                            Height = "3'9\"",
                            Hobbies = "Dolls, Music",
                            Knowledge = "[0,1,2,3,4,4,5,5,5]",
                            Might = "[0,2,2,3,3,4,4,6,7]",
                            Name = "Zoe Ingstrom",
                            Sanity = "[0,3,4,5,5,6,6,7,8]",
                            Speed = "[0,4,4,4,4,5,6,8,8]",
                            StartingKnowledge = 3,
                            StartingMight = 4,
                            StartingSanity = 3,
                            StartingSpeed = 4,
                            Weight = 49
                        },
                        new
                        {
                            Id = 9,
                            Age = 18,
                            Birthday = "August 2nd",
                            Height = "5'2\"",
                            Hobbies = "Television, Shopping",
                            Knowledge = "[0,2,3,3,4,5,6,7,8]",
                            Might = "[0,3,3,3,4,5,6,7,8]",
                            Name = "Heather Granville",
                            Sanity = "[0,3,3,3,4,5,6,6,6]",
                            Speed = "[0,3,3,4,5,6,6,7,8]",
                            StartingKnowledge = 5,
                            StartingMight = 3,
                            StartingSanity = 3,
                            StartingSpeed = 3,
                            Weight = 120
                        },
                        new
                        {
                            Id = 10,
                            Age = 21,
                            Birthday = "March 4th",
                            Height = "5'7\"",
                            Hobbies = "Reading, Soccer",
                            Knowledge = "[0,2,3,3,4,4,5,6,8]",
                            Might = "[0,3,4,4,4,4,5,6,8]",
                            Name = "Jenny LeClerc",
                            Sanity = "[0,1,1,2,4,4,4,5,6]",
                            Speed = "[0,2,3,4,4,4,5,6,8]",
                            StartingKnowledge = 3,
                            StartingMight = 3,
                            StartingSanity = 5,
                            StartingSpeed = 4,
                            Weight = 142
                        },
                        new
                        {
                            Id = 11,
                            Age = 37,
                            Birthday = "December 10th",
                            Height = "5'0\"",
                            Hobbies = "Astrology, Cooking, Baseball",
                            Knowledge = "[0,1,3,4,4,4,5,6,6]",
                            Might = "[0,2,3,3,4,5,5,5,6]",
                            Name = "Madame Zostra",
                            Sanity = "[0,4,4,4,5,6,7,8,8]",
                            Speed = "[0,2,3,3,5,5,6,6,7]",
                            StartingKnowledge = 4,
                            StartingMight = 4,
                            StartingSanity = 3,
                            StartingSpeed = 3,
                            Weight = 150
                        },
                        new
                        {
                            Id = 12,
                            Age = 42,
                            Birthday = "January 11th",
                            Height = "5'5\"",
                            Hobbies = "Old Movies, Horses",
                            Knowledge = "[0,4,5,5,5,5,6,6,7]",
                            Might = "[0,2,2,2,4,4,5,6,6]",
                            Name = "Vivian Lopez",
                            Sanity = "[0,4,4,4,5,6,7,8,8]",
                            Speed = "[0,3,4,4,4,4,6,7,8]",
                            StartingKnowledge = 4,
                            StartingMight = 3,
                            StartingSanity = 3,
                            StartingSpeed = 4,
                            Weight = 142
                        });
                });

            modelBuilder.Entity("betrayal_hill.Models.Static.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AllowedFloors")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 7,
                            AllowedFloors = 7,
                            Name = "Creaky Hallway"
                        });
                });

            modelBuilder.Entity("betrayal_hill.Models.Dynamic.InventoryItem", b =>
                {
                    b.HasOne("betrayal_hill.Models.Static.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("betrayal_hill.Models.Dynamic.PlacedRoom", "PlacedRoom")
                        .WithMany()
                        .HasForeignKey("PlacedRoomId");

                    b.HasOne("betrayal_hill.Models.Dynamic.Player", "Player")
                        .WithMany("Inventory")
                        .HasForeignKey("PlayerId");

                    b.Navigation("Card");

                    b.Navigation("PlacedRoom");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("betrayal_hill.Models.Dynamic.PlacedRoom", b =>
                {
                    b.HasOne("betrayal_hill.Models.Dynamic.Game", "Game")
                        .WithMany("PlacedRooms")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("betrayal_hill.Models.Static.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("betrayal_hill.Models.Dynamic.Player", b =>
                {
                    b.HasOne("betrayal_hill.Models.Static.Explorer", "Explorer")
                        .WithMany()
                        .HasForeignKey("ExplorerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("betrayal_hill.Models.Dynamic.Game", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Explorer");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("betrayal_hill.Models.Dynamic.Game", b =>
                {
                    b.Navigation("PlacedRooms");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("betrayal_hill.Models.Dynamic.Player", b =>
                {
                    b.Navigation("Inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
